name: HelloWorldPipeline

trigger:
  branches:
    include:
      - main

jobs:
  - job: HelloWorldJob
    displayName: "Print Hello World"
    pool:
      name: Rakesh  # Specify the name of your local agent pool here

    steps:
      - script: echo "Hello, World!"
        displayName: 'Print Hello World'
